-- PandaFit: registro de treinos. Ferramenta pessoal sem tela de login (mesmo
-- padrão do protótipo de design), então a leitura e a escrita ficam abertas
-- para o role anon — não há usuário/empresa para segmentar por linha.
create table public.pandafit_workouts (
  id bigint generated by default as identity primary key,
  date date not null,
  type text not null check (type in ('Musculação', 'Jiu Jitsu', 'Corrida')),
  minutes integer not null check (minutes > 0),
  local text not null default '',
  created_at timestamptz not null default now()
);

alter table public.pandafit_workouts enable row level security;

create policy "pandafit_workouts_anon_select"
  on public.pandafit_workouts
  for select
  to anon
  using (true);

create policy "pandafit_workouts_anon_insert"
  on public.pandafit_workouts
  for insert
  to anon
  with check (true);
