-- Registro diário de peso. `date` é unique para permitir upsert (corrigir
-- o peso do dia sem criar um segundo registro na mesma data).
create table public.pandafit_weights (
  id bigint generated by default as identity primary key,
  date date not null unique,
  weight_kg numeric(5,2) not null check (weight_kg > 0 and weight_kg < 500),
  created_at timestamptz not null default now()
);

alter table public.pandafit_weights enable row level security;

create policy "pandafit_weights_anon_select"
  on public.pandafit_weights
  for select
  to anon
  using (true);

create policy "pandafit_weights_anon_insert"
  on public.pandafit_weights
  for insert
  to anon
  with check (true);

create policy "pandafit_weights_anon_update"
  on public.pandafit_weights
  for update
  to anon
  using (true)
  with check (true);

create policy "pandafit_weights_anon_delete"
  on public.pandafit_weights
  for delete
  to anon
  using (true);
