-- Documentos: upload de exames médicos (aba "Documentos"). Bucket público —
-- coerente com o resto do PandaFit, onde toda tabela já é anon
-- select/insert/delete aberto; um bucket "privado" com as mesmas políticas
-- abertas de storage não adicionaria controle de acesso real.
create table public.pandafit_documents (
  id bigint generated by default as identity primary key,
  file_name text not null,
  file_path text not null,
  file_type text not null,
  file_size bigint not null,
  uploaded_at timestamptz not null default now()
);

alter table public.pandafit_documents enable row level security;

create policy "pandafit_documents_anon_select"
  on public.pandafit_documents for select to anon using (true);
create policy "pandafit_documents_anon_insert"
  on public.pandafit_documents for insert to anon with check (true);
create policy "pandafit_documents_anon_delete"
  on public.pandafit_documents for delete to anon using (true);

insert into storage.buckets (id, name, public)
values ('pandafit-documents', 'pandafit-documents', true)
on conflict (id) do nothing;

create policy "pandafit_documents_storage_anon_select"
  on storage.objects for select to anon
  using (bucket_id = 'pandafit-documents');
create policy "pandafit_documents_storage_anon_insert"
  on storage.objects for insert to anon
  with check (bucket_id = 'pandafit-documents');
create policy "pandafit_documents_storage_anon_delete"
  on storage.objects for delete to anon
  using (bucket_id = 'pandafit-documents');
