-- Catálogos por usuário para modalidades de treino e locais. Antes, os
-- "tipos" eram uma lista fixa no código (WORKOUT_TYPES em app.js) e o
-- "local" era só sugerido via <datalist>, calculado na hora a partir do
-- histórico de treinos — nada disso era editável nem persistido como um
-- cadastro de verdade. Agora cada usuario (e o admin, que também treina)
-- tem seu próprio catálogo, gerenciável em Configurações > Modalidades /
-- Locais, e pode adicionar quantas modalidades e locais quiser.

create table public.pandafit_workout_types (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  name text not null,
  hint text not null default '',
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table public.pandafit_locations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

alter table public.pandafit_workout_types enable row level security;
alter table public.pandafit_locations enable row level security;

-- Mesmo padrão de RLS do resto do PandaFit: só o dono mexe no próprio
-- catálogo. O médico não precisa (só lê treinos já registrados, que
-- guardam o nome da modalidade/local como texto solto).
create policy "pandafit_workout_types_select" on public.pandafit_workout_types for select
  to authenticated
  using (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_workout_types_insert" on public.pandafit_workout_types for insert
  to authenticated
  with check (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_workout_types_delete" on public.pandafit_workout_types for delete
  to authenticated
  using (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_locations_select" on public.pandafit_locations for select
  to authenticated
  using (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_locations_insert" on public.pandafit_locations for insert
  to authenticated
  with check (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_locations_delete" on public.pandafit_locations for delete
  to authenticated
  using (user_id = auth.uid() and public.pandafit_current_role() is not null);

-- Migra o histórico já existente para o novo catálogo, pra ninguém perder
-- as modalidades/locais que já usava. Sem isso, quem já tem treinos
-- registrados abriria Configurações > Modalidades/Locais e veria uma
-- lista vazia mesmo já tendo usado várias.
insert into public.pandafit_workout_types (user_id, name)
select distinct user_id, type from public.pandafit_workouts
on conflict (user_id, name) do nothing;

insert into public.pandafit_locations (user_id, name)
select distinct user_id, local from public.pandafit_workouts
where local is not null and btrim(local) <> ''
on conflict (user_id, name) do nothing;
