-- Séries, repetições e carga por exercício — o maior salto de "app de
-- duração" pra tracker de treino de força de verdade. Um treino continua
-- tendo data/tipo/duração/local, mas agora pode opcionalmente ter uma ou
-- mais entradas em pandafit_workout_sets (um exercício com N séries de
-- reps x carga cada). pandafit_exercises é o catálogo de nomes de
-- exercício por usuário, mesmo padrão de pandafit_workout_types e
-- pandafit_locations (migração 0051): "tudo que é cadastrável mora em
-- Configurações", com autocomplete e auto-cadastro ao digitar um nome novo.

create table public.pandafit_exercises (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

alter table public.pandafit_exercises enable row level security;

create policy "pandafit_exercises_select" on public.pandafit_exercises for select
  to authenticated
  using (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_exercises_insert" on public.pandafit_exercises for insert
  to authenticated
  with check (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_exercises_delete" on public.pandafit_exercises for delete
  to authenticated
  using (user_id = auth.uid() and public.pandafit_current_role() is not null);

-- Cada linha é UMA série de UM exercício dentro de um treino. Guarda o
-- nome do exercício como texto solto (não uma FK pro catálogo) — mesmo
-- motivo de pandafit_workouts.type: apagar do catálogo não pode apagar
-- nem quebrar histórico já registrado.
create table public.pandafit_workout_sets (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.pandafit_workouts(id) on delete cascade,
  user_id uuid not null references auth.users(id),
  exercise_name text not null,
  set_number integer not null check (set_number > 0),
  reps integer not null check (reps > 0),
  weight_kg numeric check (weight_kg is null or weight_kg >= 0),
  created_at timestamptz not null default now()
);

create index pandafit_workout_sets_workout_id_idx on public.pandafit_workout_sets (workout_id);

alter table public.pandafit_workout_sets enable row level security;

-- Mesmo padrão de pandafit_workouts: dono tem CRUD completo, médico só lê.
create policy "pandafit_workout_sets_select" on public.pandafit_workout_sets for select
  to authenticated
  using (
    (user_id = auth.uid() and public.pandafit_current_role() is not null)
    or public.pandafit_current_role() = 'medico'
  );

create policy "pandafit_workout_sets_insert" on public.pandafit_workout_sets for insert
  to authenticated
  with check (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_workout_sets_delete" on public.pandafit_workout_sets for delete
  to authenticated
  using (user_id = auth.uid() and public.pandafit_current_role() is not null);
