-- Fotos de progresso: o peso já tem histórico e tendência (gráfico de
-- linha); o corpo não tinha nenhum registro visual ao longo do tempo.
-- Mesmo padrão de segurança de pandafit_documents (bucket privado, signed
-- URL, pasta por usuário) mas com o mesmo modelo de acesso de
-- pandafit_weights/pandafit_workouts — médico só lê, sem download/exclusão
-- (photos ficam junto de "Registrar > Peso", não são documento médico).
create table public.pandafit_progress_photos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  file_path text not null,
  file_name text not null,
  file_type text not null,
  file_size bigint not null,
  taken_at date not null,
  uploaded_at timestamptz not null default now()
);

alter table public.pandafit_progress_photos enable row level security;

create policy "pandafit_progress_photos_select" on public.pandafit_progress_photos for select
  to authenticated
  using (
    (user_id = auth.uid() and public.pandafit_current_role() is not null)
    or public.pandafit_current_role() = 'medico'
  );

create policy "pandafit_progress_photos_insert" on public.pandafit_progress_photos for insert
  to authenticated
  with check (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_progress_photos_delete" on public.pandafit_progress_photos for delete
  to authenticated
  using (user_id = auth.uid() and public.pandafit_current_role() is not null);

insert into storage.buckets (id, name, public)
values ('pandafit-progress-photos', 'pandafit-progress-photos', false)
on conflict (id) do nothing;

create policy "pandafit_progress_photos_storage_select" on storage.objects for select
  to authenticated
  using (
    bucket_id = 'pandafit-progress-photos'
    and (
      (storage.foldername(name)) [1] = auth.uid()::text
      or public.pandafit_current_role() = 'medico'
    )
    and public.pandafit_current_role() is not null
  );

create policy "pandafit_progress_photos_storage_insert" on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'pandafit-progress-photos'
    and (storage.foldername(name)) [1] = auth.uid()::text
    and public.pandafit_current_role() is not null
  );

create policy "pandafit_progress_photos_storage_delete" on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'pandafit-progress-photos'
    and (storage.foldername(name)) [1] = auth.uid()::text
    and public.pandafit_current_role() is not null
  );
