-- Medidas corporais além do peso: cintura e % de gordura, mesmo padrão de
-- registro por data (upsert em user_id+date) que pandafit_weights já usa.
-- Versão enxuta do item de roadmap P2 — sem meta dedicada por métrica (isso
-- fica pra uma iteração futura se fizer falta), só histórico com edição e
-- indicador de variação, igual ao que o peso já tem.
create table public.pandafit_body_measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  date date not null,
  waist_cm numeric(5,1) check (waist_cm is null or (waist_cm > 0 and waist_cm < 300)),
  body_fat_pct numeric(4,1) check (body_fat_pct is null or (body_fat_pct > 0 and body_fat_pct < 100)),
  created_at timestamptz not null default now(),
  unique (user_id, date),
  constraint pandafit_body_measurements_has_value check (waist_cm is not null or body_fat_pct is not null)
);

alter table public.pandafit_body_measurements enable row level security;

create policy "pandafit_body_measurements_select" on public.pandafit_body_measurements for select
  to authenticated
  using (
    (user_id = auth.uid() and public.pandafit_current_role() is not null)
    or public.pandafit_current_role() = 'medico'
  );

create policy "pandafit_body_measurements_insert" on public.pandafit_body_measurements for insert
  to authenticated
  with check (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_body_measurements_update" on public.pandafit_body_measurements for update
  to authenticated
  using (user_id = auth.uid() and public.pandafit_current_role() is not null)
  with check (user_id = auth.uid() and public.pandafit_current_role() is not null);

create policy "pandafit_body_measurements_delete" on public.pandafit_body_measurements for delete
  to authenticated
  using (user_id = auth.uid() and public.pandafit_current_role() is not null);
